name: CI

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0
      with:
        version: 6.3.1
    - name: Run qmake
      run: qmake .
    - name: Run make
      run: make
    - name: Run QML tests
      run: ./qmltests/qmltests.app/Contents/MacOS/qmltests
    - name: Run C++ tests
      run: ./cpptests/cpptests
