name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xcb
      run: sudo apt install libxkbcommon-x11-0
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0
      with:
        version: 5.14.1
    - name: Run qmake
      run: qmake .
    - name: Run make
      run: make
    - name: Run tests
      run: QT_DEBUG_PLUGINS=1 ./tests/tests
