name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install xcb
      run: apt install xcb
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0
      with:
        version: 5.14.1
    - name: Run qmake
      run: qmake .
    - name: Run make
      run: make
    - name: Run tests
      run: ./tests/tests
